# Generated by Django 4.0.6 on 2022-08-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=100)),
                ('arquivado', models.BooleanField(default=False)),
                ('prioridade', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAIXA', 'Baixa')], default='BAIXA', max_length=5)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
